CLASS zcl_06_storage_paris DEFINITION INHERITING FROM zcl_05_plant_paris
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_storage_paris IMPLEMENTATION.
ENDCLASS.
