CLASS zcl_lab_23_company_paris DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_paris.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA capital TYPE string.
ENDCLASS.



CLASS zcl_lab_23_company_paris IMPLEMENTATION.
ENDCLASS.
