CLASS zcl_12_storage_location_paris DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_12_storage_location_paris IMPLEMENTATION.
ENDCLASS.
