CLASS zcl_lab_21_classroom_paris DEFINITION
  PUBLIC
  CREATE PROTECTED .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_21_classroom_paris IMPLEMENTATION.
ENDCLASS.
