CLASS zcl_lab_12_linux_paris DEFINITION INHERITING FROM zcl_lab_11_system_paris
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_paris IMPLEMENTATION.
ENDCLASS.
